#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

#workspaces
bspc monitor -d I II III IV V

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Polybar not shown in fullscreen
#wm-restack = bspwm

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Nemo desktop='^3' follow=on
bspc rule -a discord desktop='^4' follow=on
